### ISSUE TITLE
Not so much a bug, but more of a json payload adjustment

### ISSUE THREAD

**Issue by flipcyde** [BIG-Games-LLC/ps99-public-api-docs#1]
When ingesting the payload, I'm seeing that the data parent is holding all of the values instead of nesting them within their configData on each pet/item for RAP

It's causing the key value pairs to not align, and instead its  pulling ALL of the values under "data" per config.Data.id

![Screenshot 2024-03-11 121057](https://github.com/BIG-Games-LLC/ps99-public-api-docs/assets/39178036/e1e5b361-587d-404a-a67d-e13db5494ef0)

![Screenshot 2024-03-11 121246](https://github.com/BIG-Games-LLC/ps99-public-api-docs/assets/39178036/23536514-a8a4-4e04-b9d0-8e7ce8e1b338)

**Comment by chickenputty** [comment]
This is as indented. It's preference, but the current arrangement lets you do something like this:
```javascript
                const rapItem = rap.find((rapItem) => {
                    const configDataKeys = Object.keys(rapItem.configData);
                    return configDataKeys.length === 1 && configDataKeys[0] === 'id' && // grab normal only
                        (!collection || rapItem.category === collection) && // compare category, if it exists
                        rapItem.configData.id === configName // compare name
                });
                item.rap = (rapItem && rapItem.value) || 0;
```
This way the configData can be used to grab normal pets by checking that the configData only contains an id key.
