### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by CuteBuffy** [BIG-Games-LLC/ps99-public-api-docs#12]
Hey! I've been trying to get the data from the API, but I keep getting the same error: 

Access to fetch at 'https://biggamesapi.io/api/collection/Pets' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

The line of code where I'm trying to get it looks like this: 

  useEffect(() => {
    const getPets = async () => {
      const res = await fetch("https://biggamesapi.io/api/collection/Pets")
      const data = await res.text();
      console.log(data)
    }
    getPets();
  }, [])

setting mode to "no-cors" is not helping, it just gives me empty line when consoling data.

**Comment by Julli4n** [comment]
you'll need to create a web server to proxy and supply CORS to access it

> setting mode to "no-cors" is not helping, it just gives me empty line when consoling data.
`no-cors` is if you don't need to see the response, don't use it.

**Comment by CuteBuffy** [comment]
Hey! I searched it up a little bit, and came up with this solution: 

in vite.config.js:
  server: {
    port: 3000,
    proxy: {
      "/api": {
        target: "https://biggamesapi.io/api/collection/Pets",
        changeOrigin: true,
        secure: false,
        changeOrigin: true,
        rewrite: path => path.replace(/^\/api/, '')
      },
    },
  },

in app:
  useEffect(() => {
    const getPets = async () => {
      const res = await fetch("/api")
      const data = await res.json();
      setPetsData(data)
    }
    getPets()
  }, [])

it's working now, but i'm not sure if it's the way to go.

**Comment by CuteBuffy** [comment]
well, it worked with proxy on local server, but when deployed to github it's not working. Any ideas?

**Comment by chickenputty** [comment]
I have no idea what Vite is. Google says, “vite ignores proxy settings in production”. I suggest using Google, Vite support, or ChatGPT. This issue doesn’t pertain to the API itself.

**Comment by CuteBuffy** [comment]
Well, yeah, the second problem wasn't really related to the api, sorry. Great API though, thank you so much for it!

**Comment by Soap-0020** [comment]
im having this issue too... i believe you can use the cors library to allow for easier access for websites to use the api @chickenputty

**Comment by chickenputty** [comment]
@Soap-0020 Oh I see, I just now pushed headers to allow cross-origin requests

**Comment by Soap-0020** [comment]
appreciate it, works now
