### ISSUE TITLE
Add Icon for every Enchant and Egg

### ISSUE THREAD

**Issue by 5XS** [BIG-Games-LLC/ps99-public-api-docs#16]
**Is your feature request related to a problem? Please describe.**
No, but it will improve the experience of using APE

**Describe the solution you'd like**
Add every egg and enchant

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by SteampunkWizardStudios** [comment]
You can use your own icon by getting the roblox asset id for now.

**Comment by chickenputty** [comment]
We don't have photos of every egg as we don't use them in-game. It is best to maintain these yourself.

Enchant images can be found in `/api/collections/Enchants`. This data is structured a bit differently due to the tiers.

**Comment by 5XS** [comment]
> We don't have photos of every egg as we don't use them in-game. It is best to maintain these yourself.
> 
> Enchant images can be found in `/api/collections/Enchants`. This data is structured a bit differently due to the tiers.

Most enchants have https://biggamesapi.io/image/13824100032 as their PageIcon

**Comment by chickenputty** [comment]
> > We don't have photos of every egg as we don't use them in-game. It is best to maintain these yourself.
> > Enchant images can be found in `/api/collections/Enchants`. This data is structured a bit differently due to the tiers.
> 
> Most enchants have https://biggamesapi.io/image/13824100032 as their PageIcon

PageIcons are not used. The icons are under each tier - such as: `configData.Tiers[0].Icon`.
