### ISSUE TITLE
Collection "Events"

### ISSUE THREAD

**Issue by 5XS** [BIG-Games-LLC/ps99-public-api-docs#17]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The collection will have all active and inactive events, such as St. Patrick's Day and Christmas.

**Describe alternatives you've considered**
You can also do the current event as an alternative

**Comment by SteampunkWizardStudios** [comment]
Also, random events like comets or coin jars

**Comment by chickenputty** [comment]
> Also, random events like comets or coin jars

There is `/api/collections/RandomEvents` already.

**Comment by chickenputty** [comment]
Regarding OP, this will not happen, sorry.
