### ISSUE TITLE
Collection "Updates"

### ISSUE THREAD

**Issue by 5XS** [BIG-Games-LLC/ps99-public-api-docs#18]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The collection contains update dates and changelogs, as well as the date of the future update if there is a timer

**Comment by chickenputty** [comment]
I can add the changelogs, but it will be a bit of work. I'll leave this open for now.

**Comment by chickenputty** [comment]
I lied, this data is not going to be supported. It's simply too deep in the codebase and out of the scope of this API. Changelogs can be viewed on our blog.
