### ISSUE TITLE
Collection "Merchants"

### ISSUE THREAD

**Issue by 5XS** [BIG-Games-LLC/ps99-public-api-docs#19]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
This collection contains information about merchants as well as the date of the next reload of content

**Describe alternatives you've considered**
Create an /api/merchants endpoint with the next merchant reboot dates.

**Comment by chickenputty** [comment]
I've added `/api/collection/Merchants`. The refresh rate timer is there, but it's based on the server (as far as I know).
