### ISSUE TITLE
Countdown for timed events

### ISSUE THREAD

**Issue by tommyplaysyt** [BIG-Games-LLC/ps99-public-api-docs#22]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
New API with or without a countdown to current events. For example, with the St. Patricks event, the API counts down until the next event occurs, or simply states the UTC time of when the next event will occur.

**Additional context**
Not sure if this is a duplicate or not. Also this would only be useful when timed events such as St. Patricks limited time events are running.

**Comment by chickenputty** [comment]
Sorry, this won't happen as it's not something easily maintained for us. You can reference the times from the blog and create your own timer. For example, the St. Patrick's event is every 4 hours from 2PM CST.

**Comment by tommyplaysyt** [comment]
Gotcha, thanks for the fast response.

**Comment by SteampunkWizardStudios** [comment]
@tommyplaysyt if you end up making your own timers can you make it available through an API?
