### ISSUE TITLE
Hoverboard Exist Implementation + api support

### ISSUE THREAD

**Issue by tommyplaysyt** [BIG-Games-LLC/ps99-public-api-docs#23]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Add exist tracking for hoverboards, both Shiny and Normal.

**Additional context**
Would require implementation scripting in-game as well, and an API to go along with this would be awesome.

**Comment by chickenputty** [comment]
If the data is not exposed in-game, we won't expose it on the API. Sorry
