### ISSUE TITLE
Active Huge Egg

### ISSUE THREAD

**Issue by Soap-0020** [BIG-Games-LLC/ps99-public-api-docs#25]
**Describe the bug**
The API for the Active Huge Egg is showing the wrong pets

**Expected behavior**
Egg show the current active huges

**Screenshots**
![image](https://github.com/BIG-Games-LLC/ps99-public-api-docs/assets/110540103/a8c95615-d6ea-405e-b44e-8df6f0984b5a)
![image](https://github.com/BIG-Games-LLC/ps99-public-api-docs/assets/110540103/629bce99-a78a-49ea-aabd-4759e671650b)

**Comment by chickenputty** [comment]
This sadly won't update. It will only update when we update the game. There is no way to know the active huge pets right now unless you track exists going up.

**Comment by Soap-0020** [comment]
any chance you could add an endpoint for the current active huges then?

**Comment by chickenputty** [comment]
Hopefully eventually

**Comment by chickenputty** [comment]
Update. We will not support this due to it being dynamic data that is not stored externally. There are ways to figure out which are active through their exists count and such. View ps99rap.com for example.
