### ISSUE TITLE
Inaccurate User Data Retrieval in Clans API

### ISSUE THREAD

**Issue by Alfred-GitHub1** [BIG-Games-LLC/ps99-public-api-docs#26]
Thank you for providing this API. I've been using it extensively, but it appears that the Clans API may have a bug. When requesting information about a specific guild, it returns users who left days ago. Could you please address this issue? Thank you!

**Comment by chickenputty** [comment]
A lot of their data is retained, like diamonds donated. The member list for the clan is accurate to who is in it.

**Comment by chickenputty** [comment]
Going to assume this was the case
