### ISSUE TITLE
Quests from a person in the API?

### ISSUE THREAD

**Issue by KDBgames** [BIG-Games-LLC/ps99-public-api-docs#29]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
like, I want to be able to get the quest from a player back, and how many the player need to compleet before the quest is done.
For example: your quests is 'Hatch 1500 of your best eggs' then the API needs to give back [Quest title], [Quest tier], [Quest Progress]

**Comment by SteampunkWizardStudios** [comment]
Chickenputty said that there will not be any player data available for the time being.

**Comment by chickenputty** [comment]
Directing all this discussion here https://github.com/BIG-Games-LLC/ps99-public-api-docs/issues/5
