### ISSUE TITLE
Diminish Power

### ISSUE THREAD

**Issue by Soap-0020** [BIG-Games-LLC/ps99-public-api-docs#30]
**Question**
How would i calculate the amount of total power while factoring diminishing power?

**Comment by chickenputty** [comment]
Power of what? Not sure if I can answer as so many calculations come into play

**Comment by chickenputty** [comment]
Hmm, knowing specific calculations may be exposing too much of the inner workings of the game. I don't think we are going to detail how things like that work. Sorry

**Comment by Soap-0020** [comment]
all good! ill have to test it myself then haha
