### ISSUE TITLE
Clan Overview Page Bug

### ISSUE THREAD

**Issue by Soap-0020** [BIG-Games-LLC/ps99-public-api-docs#33]
**Describe the bug**
When making a request to the clan api with the same pagesize, each page has a few duplicated clans

**To Reproduce**
Make a https request to
>  "https://biggamesapi.io/api/clans?page=2&pageSize=1000&sort=Points&sortOrder=desc"
and
> https://biggamesapi.io/api/clans?page=3&pageSize=1000&sort=Points&sortOrder=desc

Then look for duplicate clan names

**Expected behavior**
They dont show the same clan on multiple pages

**Screenshots**
![image](https://github.com/BIG-Games-LLC/ps99-public-api-docs/assets/110540103/208876fd-d531-4b9e-b6ac-5b6c8a4f5ba3)
![image](https://github.com/BIG-Games-LLC/ps99-public-api-docs/assets/110540103/ac728835-5096-4bb7-a35b-097e1bbc4173)

**Comment by Soap-0020** [comment]
still an issue

**Comment by chickenputty** [comment]
I can't reproduce and the code seems straight forward on the API end. Only thing I can think is the cache may be causing this. Can you show a new example?

**Comment by chickenputty** [comment]
Inactive thread
