### ISSUE TITLE
Is there a way I can access my own personal account and track the items that I gain?

### ISSUE THREAD

**Issue by JacksonXu159** [BIG-Games-LLC/ps99-public-api-docs#36]
**Question**
I want to be able to create a web app to track the items in my inventory, the on status of me, and basically the P/L of the rap of my stuff of my account. Is there a way to do that with this API, or is it more general.

**Comment by chickenputty** [comment]
This is not possible at the moment.

https://github.com/BIG-Games-LLC/ps99-public-api-docs/issues/5#issuecomment-1989614992
