### ISSUE TITLE
Mass Clan Data

### ISSUE THREAD

**Issue by Soap-0020** [BIG-Games-LLC/ps99-public-api-docs#37]
**Question**
Im currently working on a project that will require mass clan data collection, how would i do this without getting ip banned or spamming the api/could there be a way to get more then 1 clan details in a bulk clan get request possibly (that provides more info then the current one)?

**Comment by SteampunkWizardStudios** [comment]
Hey! I'm one of these developers and would like to know also.

**Comment by chickenputty** [comment]
As far as I know, a bulk endpoint would generate the same stress on our systems as spamming lookups does.

The solution ultimately is to slowly build up a cache of data or re-think the structure of project.

**Comment by Soap-0020** [comment]
alright

**Comment by samloft** [comment]
Depending on what you are doing, you may not need most clan data and certainly not live data.

Let's say you are building a clan page for people to use during wars.

Why would you want all the data? Store the clan "header" data so you know what clans exist, then using something like websockets you know when someone is viewing a clan, so can live update the data for populated channels.

So you would 

- Check the populated channels (clans)
- Run an update to store your data for these populated clans
- Push the updated data to the populated channels
