### ISSUE TITLE
Post requests

### ISSUE THREAD

**Issue by Angulorecto** [BIG-Games-LLC/ps99-public-api-docs#39]
Can we create ways to manage data in ps99 via the api? For example I can create a way to easily create, add diamonds, edit and disband my clan? To implement this we have to add a key or something tied to your account that only you can see so that you and only you can send post requests.

**Comment by chickenputty** [comment]
Not currently, please refer to https://github.com/BIG-Games-LLC/ps99-public-api-docs/issues/5#issuecomment-1989614992
