### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by Soulivan71** [BIG-Games-LLC/ps99-public-api-docs#40]
**Question**
I want to do a bot and get some things :
- Huge active rotation (time remaining) (display icon/name/price of selling)
- All pets in game (Like name/Price of selling/Numbers of existing ig/Categories (Huge/Shyny/Gold))
I want to do a discord bot. But I don't know how to get images for example etc.
Can anyone help me by giving many details as u can ? :3

**Environment (if applicable)**
- Version: discord python

Tysm if anyone can take time to help me.

**Comment by SteampunkWizardStudios** [comment]
Hey this isn't the place to ask for help with discord bots but if you're interested you could join my ps99 dev server, I've got about 9 or 10 devs and we collab and help out.

**Comment by Soulivan71** [comment]
Ok but if there is a Support tag its for this no ? Can u give me ? (My ds : soulivan71)

> Hey this isn't the place to ask for help with discord bots but if you're interested you could join my ps99 dev server, I've got about 9 or 10 devs and we collab and help out.

**Comment by Soulivan71** [comment]
@SteampunkWizardStudios ?

**Comment by flipcyde** [comment]
@SteampunkWizardStudios whats your discord?

**Comment by SteampunkWizardStudios** [comment]
> @SteampunkWizardStudios whats your discord?

It's steampunkWizard

**Comment by xXGigaXx** [comment]
> > @SteampunkWizardStudios whats your discord?
> 
> It's steampunkWizard

Hello I added you if that's ok. I'm new to coding but am attempting to figure out how to pull loot tables and a few other things. xgigabytex is my discord user

**Comment by chickenputty** [comment]
Sorry huge active rotation won't be added due to it being dynamic data that isn't stored externally. There are ways to figure it out with the data we do serve though. View ps99rap.com
