### ISSUE TITLE
Missing some pets image

### ISSUE THREAD

**Issue by Soulivan71** [BIG-Games-LLC/ps99-public-api-docs#41]
Im looking for image of :
Black Hole Angelus (Raimbow/ShinyRaimbow/ShinyGold) but not available or Im blind 
Titanic Black Hole Angelus existing in raimbow ? (Can't fetch the images too)

**Comment by chickenputty** [comment]
There are not icons for rainbow and shiny.
- Rainbow pets use the gold icon with hue changes
- Shiny pets use the regular (or gold) icon with a shiny overlay

 A suggestion on how to implement the effects with CSS -> https://github.com/BIG-Games-LLC/ps99-public-api-docs/issues/2#issuecomment-1989500146

**Comment by Soulivan71** [comment]
> There are no icons for rainbow and shiny.
> 
> * Rainbow pets use the gold icon with hue changes
> * Shiny pets use the regular (or gold) icon with a shiny overlay
> 
> A suggestion on how to implement the effects with CSS -> [#2 (comment)](https://github.com/BIG-Games-LLC/ps99-public-api-docs/issues/2#issuecomment-1989500146)

Yeah for shiny I know how to but I don't understand hue changes.
Btw I mention u on twitter idk if u see my issue with pet official bot.
