### ISSUE TITLE
Incorrect Placement Position

### ISSUE THREAD

**Issue by jcool3413** [BIG-Games-LLC/ps99-public-api-docs#44]
**Describe the bug**
The placement field of a clan battle is incorrect compared to the clans endpoint.

**To Reproduce**
When running _https://biggamesapi.io/api/clans?page=1&pageSize=72&sort=Points&sortOrder=desc_ the clan **24z** is 47th place.

However, when using the /clan endpoint the clan **24z** is 71th place.

**Expected behavior**
Both numbers should be equal.

**Screenshots**
![image](https://github.com/BIG-Games-LLC/ps99-public-api-docs/assets/113404215/c8b2e15d-2a78-4a2a-b515-712fdb65cf43)
![image](https://github.com/BIG-Games-LLC/ps99-public-api-docs/assets/113404215/e82d90d1-4a84-4d2c-ab47-438ce57d64bc)

**Additional context**
Placement bug is also visible in game.

![image](https://github.com/BIG-Games-LLC/ps99-public-api-docs/assets/113404215/342548b3-9948-4207-a7c1-7781bdebab41)
![image](https://github.com/BIG-Games-LLC/ps99-public-api-docs/assets/113404215/78f8feb9-4f63-4362-ae70-ba0ddb9fbe29)

**Comment by Alfred-GitHub1** [comment]
i have the same issue

**Comment by chickenputty** [comment]
I can't seem to replicate. Was this during the start of the contest? The data could have been cached at different times

**Comment by Vinsterplays** [comment]
Happened to me around when the battle started. After around 12 hours it fixed itself and it seemed to only happen to a few clans.

**Comment by jcool3413** [comment]
Same thing happened to my own clan **j**, within the /clan endpoint my clan is supposedly at #484 place. However, running the /clans endpoint, I can't even find my clan in the top 1,000.

**Comment by chickenputty** [comment]
This is because the endpoints are caching at different points. They will sync up eventually.

**Comment by Vinsterplays** [comment]
After looking back at my logs the /clansList endpoint had the correct and updated positions for clans but the /clan endpoints clan battle position was frozen for the first 27 hours of the clan battle before it fixed itself.
![IMG_0404](https://github.com/BIG-Games-LLC/ps99-public-api-docs/assets/84172061/098de051-af66-4019-8fec-afb88f274626)

**Comment by Alfred-GitHub1** [comment]
Adam fixed the Place Key, its showing now the correct Rank.

**Comment by jcool3413** [comment]
Fixed #47
