### ISSUE TITLE
[for future] Authorization of other users for further tracking of them

### ISSUE THREAD

**Issue by 5XS** [BIG-Games-LLC/ps99-public-api-docs#45]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Authorization of other users for further tracking of them. Confirmation must be weekly for user safety and user can choose which Collections they want to share with developers. (like Discord OAuth)

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by SteampunkWizardStudios** [comment]
Chickenputty has said that he has already considered adding an endpoint for players, but said it will probably not happen soon. (Chickenputty if you see this- hire me or soap to do it)

**Comment by chickenputty** [comment]
Targeting all this discussion here https://github.com/BIG-Games-LLC/ps99-public-api-docs/issues/5
