### ISSUE TITLE
API Sorting Issue: Clans Not Sorted by Points in Descending Order

### ISSUE THREAD

**Issue by Alfred-GitHub1** [BIG-Games-LLC/ps99-public-api-docs#46]
https://biggamesapi.io/api/clans?page=1&pageSize=10&sort=Points&sortOrder=desc

this isnt sorting anymore the best clans, it just takes randoms now.

Reproduce: Just click the link and watch the stars in the latest Battle...

**Comment by flipcyde** [comment]
Can confirm this as well

**Comment by chickenputty** [comment]
Fixed now, sorry I broke it during some query optimizations last night
