### ISSUE TITLE
Wrong Placement in Clan endpoint

### ISSUE THREAD

**Issue by Alfred-GitHub1** [BIG-Games-LLC/ps99-public-api-docs#47]
To reproduce:
https://biggamesapi.io/api/clans?page=1&pageSize=50&sort=Points&sortOrder=desc **Shows Rank 34 (If you count up/down)**
https://biggamesapi.io/api/clan/caca **Shows Rank 43**

**Comment by chickenputty** [comment]
They were cached at different times

**Comment by Vinsterplays** [comment]
How often does each endpoint update now?

**Comment by Alfred-GitHub1** [comment]
> They were cached at different times

This is not the issue; it has been off by 10-15 places for a week. As you can see in the other three posts, other people have had the same problem. You don't change 15 places in an hour or even four hours of caching.

Please take a look into this!

Thanks.

Yesterday; Real Place: 34, api/clan shows 43.
Today: Real Place 36, api/clan shows 43.

**Comment by chickenputty** [comment]
Oh I see.

This data is populated by sorting the data:
https://biggamesapi.io/api/clans?page=1&pageSize=50&sort=Points&sortOrder=desc

This data is populated in-game somehow:
https://biggamesapi.io/api/clan/caca
I didn't even really realize it had this 'Place' key

I'll look into how the in-game one is different than the sorted rank

**Comment by chickenputty** [comment]
@Alfred-GitHub1 During your sample data, what is their place shown as in-game? 43 right?

**Comment by chickenputty** [comment]
This has been fixed, let me know thank you
