### ISSUE TITLE
Item Background

### ISSUE THREAD

**Issue by prodbyeagle** [BIG-Games-LLC/ps99-public-api-docs#49]
**Question**
Is there an way to get the backgorund of the Items / Huges?
Its the line in the Background

![grafik](https://github.com/BIG-Games-LLC/ps99-public-api-docs/assets/124641014/6443e84c-b119-410d-bca5-a7eab6bcdf09)

**Comment by SteampunkWizardStudios** [comment]
I agree this would be a useful feature, also the stars please

**Comment by chickenputty** [comment]
I've attached the scribble background image. You may get the colors from the [rarity collection endpoint](https://biggamesapi.io/api/collection/Rarity).

![Empty Slot](https://github.com/BIG-Games-LLC/ps99-public-api-docs/assets/1813460/0faa9860-3465-4b6b-a178-f767395205fb)

**Comment by chickenputty** [comment]
> I agree this would be a useful feature, also the stars please

Attached stars and titanic crown:
[Stars.zip](https://github.com/BIG-Games-LLC/ps99-public-api-docs/files/15493573/Stars.zip)

**Comment by prodbyeagle** [comment]
Thanks. Last question. some raritys have an gradient as color but there is only one for example in Celestial. Is there an Way to get those HEX Values? 

Have an Nice Day!

**Comment by SteampunkWizardStudios** [comment]
Yes, I would like to know for my resources as well.

**Comment by chickenputty** [comment]
Singular colors (non-gradients) were added a bit ago. I'll keep this open for the gradient request itself.
