### ISSUE TITLE
Experience Tables for Everything in game

### ISSUE THREAD

**Issue by Dev-Spadow** [BIG-Games-LLC/ps99-public-api-docs#51]
**Question**
Curiously, is the algorithm for calculating experience per level/to next level this?
```java
            int points = 0;
            int output = 0;
            for (int lvl = 1; lvl <= level; lvl++) {
                points += Math.floor(lvl + 300.0 * Math.pow(2.0, lvl / 7.0));
                if (lvl >= level) {
                    return output;
                }
                output = (int) Math.floor(points / 4);
            }
``` 

**Additional Information**
While looking around last night I noticed to variables that made me think. 83 Experience on Start, 1.2M Experience at 99. It got me thinking. What other game has these 2 consistent values?, Runescape.

**Expected Outcome**
Just more so want confirmation that the experience tables for 1-99 share the same experience tables as Runescape.

**Comment by chickenputty** [comment]
It is similar to Runescape, yes
