### ISSUE TITLE
rbxassetid in Rap Endpoint

### ISSUE THREAD

**Issue by Alfred-GitHub1** [BIG-Games-LLC/ps99-public-api-docs#52]
Hey Adam,

Could you please add rbxassetid to the RAP data?

It's a hassle constantly dealing with different API endpoints and transforming them due to the lack of organization in the API.

This change would help many people a lot.

Thank you!

**Comment by chickenputty** [comment]
Nope, thanks for asking though :D

**Comment by Alfred-GitHub1** [comment]
> Nope, thanks for asking though :D

This could significatly reduce the API calls instead of doing this:

`        public static async Task FillCache() {
            existJson = JObject.Parse(await Globals.FetchData($"https://biggamesapi.io/api/exists"));
            rapJson = JObject.Parse(await Globals.FetchData($"https://biggamesapi.io/api/rap"));
            petJson = JObject.Parse(await Globals.FetchData($"https://biggamesapi.io/api/collection/Pets"));
            enchantJson = JObject.Parse(await Globals.FetchData($"https://biggamesapi.io/api/collection/Enchants"));
            ultimateJson = JObject.Parse(await Globals.FetchData($"https://biggamesapi.io/api/collection/Ultimates"));
            fruitsJson = JObject.Parse(await Globals.FetchData($"https://biggamesapi.io/api/collection/fruits"));
            boothsJson = JObject.Parse(await Globals.FetchData($"https://biggamesapi.io/api/collection/booths"));
            potionsJson = JObject.Parse(await Globals.FetchData($"https://biggamesapi.io/api/collection/Potions"));
            hoverboardsJson = JObject.Parse(await Globals.FetchData($"https://biggamesapi.io/api/collection/hoverboards"));
            charmsJson = JObject.Parse(await Globals.FetchData($"https://biggamesapi.io/api/collection/charms"));
            miscItemsJson = JObject.Parse(await Globals.FetchData($"https://biggamesapi.io/api/collection/miscitems"));
            eggsJson = JObject.Parse(await Globals.FetchData($"https://biggamesapi.io/api/collection/eggs"));
            lootboxesJson = JObject.Parse(await Globals.FetchData($"https://biggamesapi.io/api/collection/Lootboxes"));
            seedsJson = JObject.Parse(await Globals.FetchData($"https://biggamesapi.io/api/collection/Seeds"));
        }`
        
        But okay, not my API
