### ISSUE TITLE
Written consent for API

### ISSUE THREAD

**Issue by JacksonPrazak** [BIG-Games-LLC/ps99-public-api-docs#54]
Hi!

I was reading the terms and noticed you must have written consent to use the API commercially. I am currently creating my first ever website that will display pet and item prices in PS99. I'm using it mainly as a learning project, but I do plan to put ads on it. I already have given attribution to Big Games LLC within the website, but how can I get this written consent? Thanks!

**Comment by chickenputty** [comment]
Permission granted 😎

**Comment by JacksonPrazak** [comment]
Thanks! 😄
