### ISSUE TITLE
API Wrong Title

### ISSUE THREAD

**Issue by prodbyeagle** [BIG-Games-LLC/ps99-public-api-docs#57]
**Describe the bug**
Missing Text instead of Safety Hoverboard and Booth there is only "Safety"

**Screenshot**

![image](https://github.com/BIG-Games-LLC/ps99-public-api-docs/assets/124641014/f12d6ee4-956b-4fa4-ba86-f706a1735e5e)

**Comment by chickenputty** [comment]
That's just how it works. You can assume the prizes are always hoverboard, booth, etc.
