### ISSUE TITLE
how would i get the rap value of certain pet thru command? 

### ISSUE THREAD

**Issue by MrX-On-Discord** [BIG-Games-LLC/ps99-public-api-docs#59]
hello, i am trying to make a bot in python to read certain pets and return their rap value. i cant seem to figure out how to make it to where when someone does like !rHuge Rock  then itll return the rap values of all rocks or something like that. if someone could help me thatll be cool!

**Comment by prodbyeagle** [comment]
can you send my the code you are talking about?

**Comment by chickenputty** [comment]
Thread inactive
