### ISSUE TITLE
undefined stuff on Commands.

### ISSUE THREAD

**Issue by StormedDeeps** [BIG-Games-LLC/ps99-public-api-docs#6]
Hey, So I've made a bot using the Biggames API, Though i'm Encountering this issue: The RAP for Cat is undefined. Which Means that it isn't defined from the API Website itself. if you can maybe give me a link to those values etc. cause rn i'm just fetching it from here: fetch(https://biggamesapi.io/api/collections/${argument}) a.k.a https://biggamesapi.io/api/collections/[pet] The Code For the bot Is:

const { Client, Intents } = require('discord.js');
const fetch = require('node-fetch');

const client = new Client({
    intents: [
        Intents.FLAGS.GUILDS,
        Intents.FLAGS.GUILD_MESSAGES,
        Intents.FLAGS.DIRECT_MESSAGES
    ]
});

client.on('messageCreate', message => {
    const command = message.content.split(' ')[0];
    const argument = message.content.split(' ')[1];

    switch (command) {
        case '!rap':
            fetch(`https://biggamesapi.io/api/collections/${argument}`)
                .then(response => response.json())
                .then(data => {
                    const rap = data.rap;
                    console.log(`The RAP for ${argument} is ${rap}`); // Added this line
                    message.channel.send(`The RAP for ${argument} is ${rap}`);
                })
                .catch(error => {
                    console.error('Error:', error);
                });
            break;
       case '!pet':
    fetch(`https://biggamesapi.io/api/pets/${argument}`)
        .then(response => response.json())
        .then(data => {
            console.log(data); // Log the entire data object
            const petInfo = `Pet ${argument} has ${data.stats} stats and ${data.rarity} rarity.`;
            console.log(petInfo);
            message.channel.send(petInfo);
        })
        .catch(error => {
            console.error('Error:', error);
        });
    break;

        case '!item':
            fetch(`https://biggamesapi.io/api/items/${argument}`)
                .then(response => response.json())
                .then(data => {
                    const itemInfo = `Item ${argument} has ${data.description}.`;
                    console.log(itemInfo); // Added this line
                    message.channel.send(itemInfo);
                })
                .catch(error => {
                    console.error('Error:', error);
                });
            break;
    }
});

client.login('Token');

I'm new with the API So Yeah i might need help here

**Comment by chickenputty** [comment]
Your code is doing https://biggamesapi.io/api/cat which is not a valid endpoint. In fact, none of the 3 endpoints in your code are valid. Refer to the docs https://docs.biggamesapi.io/.

The RAP endpoint is https://biggamesapi.io/api/rap. You will need to fetch this and find the cat from that data set.

**Comment by StormedDeeps** [comment]
> Your code is doing https://biggamesapi.io/api/cat which is not a valid endpoint. In fact, none of the 3 endpoints in your code are valid. Refer to the docs https://docs.biggamesapi.io/.
> 
> The RAP endpoint is https://biggamesapi.io/api/rap. You will need to fetch this and find the cat from that data set.

Alright thanks.
