### ISSUE TITLE
https://biggamesapi.io/api/clans? and "Place" again out of Synch

### ISSUE THREAD

**Issue by Alfred-GitHub1** [BIG-Games-LLC/ps99-public-api-docs#60]
https://biggamesapi.io/api/clans?page=1&pageSize=30&sort=Points&sortOrder=desc

We had this issue before.
https://biggamesapi.io/api/clans?page=1&pageSize=30&sort=Points&sortOrder=desc
in this endpoint we are on 21.

In the https://biggamesapi.io/api/clan/caca endpoint it says
        "Place": 17

**Comment by chickenputty** [comment]
I am assuming they are cached at different times unless we have that but back again.

**Comment by chickenputty** [comment]
Never mind, I was incorrect. This was from points being tied.

The in-game system (/clan place) was sub-sorting by diamonds and the API was not (/clans place).

It is now fixed, let me know. Thanks.
