### ISSUE TITLE
Actively hatched out huges

### ISSUE THREAD

**Issue by Danil6395** [BIG-Games-LLC/ps99-public-api-docs#61]
I want to make a discord bot that will write actively hatched out Huges of specific players. Wrote in the chat if the player hatched out huge

**Comment by chickenputty** [comment]
Impossible with our API. You would have to write a Roblox bot to read the chat which is against ToS - as far as I know.

**Comment by Soap-0020** [comment]
you could add it to the api

**Comment by SteampunkWizardStudios** [comment]
> you could add it to the api

Fr
