### ISSUE TITLE
Missing Xp Potion in collection/Potions

### ISSUE THREAD

**Issue by CoolerProYT** [BIG-Games-LLC/ps99-public-api-docs#63]
**Question**
Missing Xp Potion in collection/Potions

**Expected Outcome**
the colection/Potions route should include 4 of the XP Potions too.

**Comment by chickenputty** [comment]
Added now, they are under a different collection called XPPotions https://biggamesapi.io/api/collection/XPPotions

**Comment by CoolerProYT** [comment]
Ok, thanks!

**Comment by Soulivan71** [comment]
> Added now, they are under a different collection called XPPotions https://biggamesapi.io/api/collection/XPPotions

Can u update the documentation, I can find the : https://biggamesapi.io/api/collection/XPPotions in it

**Comment by Soulivan71** [comment]
> Added now, they are under a different collection called XPPotions https://biggamesapi.io/api/collection/XPPotions

Hello !
Can u update the documentation with all endpoints, I can find the : https://biggamesapi.io/api/collection/XPPotions in it

Only this is available : ![image](https://github.com/user-attachments/assets/0d561b8c-92b3-474f-bb24-1cb9d418ea07)

@chickenputty
