### ISSUE TITLE
Profile Stats!

### ISSUE THREAD

**Issue by flipcyde** [BIG-Games-LLC/ps99-public-api-docs#64]
Will we be getting the profile stats? That would be awesome to track!

**Comment by SteampunkWizardStudios** [comment]
Hey flip, I'm pretty sure chickenputty said player-related endpoints have been considered to be added in the future but I don't think they're working on it.

**Comment by flipcyde** [comment]
> Hey flip, I'm pretty sure chickenputty said player-related endpoints have been considered to be added in the future but I don't think they're working on it.

Yeah in another issue they said they wouldn't do player data at all, but being as its now public on a profile it would be cool to showcase that

**Comment by chickenputty** [comment]
Directing all player data requests to this thread https://github.com/BIG-Games-LLC/ps99-public-api-docs/issues/5
