### ISSUE TITLE
Retain old clan battle contributions

### ISSUE THREAD

**Issue by Vinsterplays** [BIG-Games-LLC/ps99-public-api-docs#66]
Currently if someone leaves a clan all their previous battle contributions are wiped from the api. Would it be possible to change this so that those old contributions arent wiped?

**Comment by littlejbirdie** [comment]
I would also like to be able to view historical clan data.  im looking for my contributions from a particular battle in a clan i was in previously, but any data i pull only shows current members. Is there a way this is stored somewhere by userid?

**Comment by Vinsterplays** [comment]
I would love to see the new stats in the trading plaza be accessible from the API too. Maybe have an API access privacy option in the in game settings similar to how hypixel skyblock does it?

**Comment by chickenputty** [comment]
No, this is not how clans function at the core. You leave - the points leave. Feel free to track your own historical data.
