### ISSUE TITLE
Exclusive Pets

### ISSUE THREAD

**Issue by RyanStudioo** [BIG-Games-LLC/ps99-public-api-docs#67]
**Is your feature request related to a problem? Please describe.**
Hello, I was working on setting pet categories for pets and noticed that exclusives pets aren't categorised, not given any details on what egg it came from or anything else

**Describe the solution you'd like**
I'd like for exclusive pets to be categorised as Exclusive, and get information on what exclusive egg it came from and etc

Thanks!

**Comment by wa1ker38552** [comment]
They are categorized in the https://biggamesapi.io/api/collection/Pets endpoint. Check for the `exclusiveLevel` key. You can also fetch the collection/eggs endpoint to get the egg it came from.
