### ISSUE TITLE
https://biggamesapi.io/api/clans?page=1&pageSize=100&sort=Points&sortOrder=desc is down

### ISSUE THREAD

**Issue by flipcyde** [BIG-Games-LLC/ps99-public-api-docs#68]
The overall clans API is down

https://biggamesapi.io/api/clans?page=1&pageSize=100&sort=Points&sortOrder=desc

{"status":"error","error":{"message":"Could not fetch clans, try again later!","ignore":true}}

**Comment by chickenputty** [comment]
Fixed, the clan points are overflowing an integer. Beware.
