### ISSUE TITLE
Webhooks? Events?

### ISSUE THREAD

**Issue by leafranger** [BIG-Games-LLC/ps99-public-api-docs#69]
**Question**
I would like to know if there's any official support for webhooks or events to get data as soon as it changes

**Additional Information**
I'm trying to fetch some data but for precision I'd like to get it as soon as it changes, instead of doing useless calls

**Comment by flipcyde** [comment]
Code for change instead of appending the same data - I have plenty of bots that look for change in points and produce events accordingly.

![image](https://github.com/user-attachments/assets/893dc577-6cd4-4c4a-b4b0-4e6c96884b48)

**Comment by chickenputty** [comment]
We will never add webhooks to this API. It is simply out of scope for what the project is. It would probably cost more than what it is worth, hard to maintain, and hard to implement for something we have no internal use for.
