### ISSUE TITLE
Credit To Devs

### ISSUE THREAD

**Issue by Soap-0020** [BIG-Games-LLC/ps99-public-api-docs#7]
**Question**
Hey! Im currently working on an API wrapper for this. I have noticed that in the terms i have to give credit to big games developers. What options do i have for this?

**Comment by chickenputty** [comment]
If you mention Pet Simulator or BIG Games you are good. We just want people to understand the data is coming from the game.

**Comment by flipcyde** [comment]
![image](https://github.com/BIG-Games-LLC/ps99-public-api-docs/assets/39178036/d4cec51f-963e-4fb9-97fc-48664dbb9669)
Would the link up top suffice?

**Comment by chickenputty** [comment]
Yes that is fine, thank you. Your dashboard looks great so far!

**Comment by Soap-0020** [comment]
making good progress with my api wrapper! what should i call it?
![image](https://github.com/BIG-Games-LLC/ps99-public-api-docs/assets/110540103/70d3b597-b11b-43fe-8bac-45bc33ef239d)
