### ISSUE TITLE
All Clan Names are in Lowercase

### ISSUE THREAD

**Issue by socutewhitebear** [BIG-Games-LLC/ps99-public-api-docs#70]
# **Describe the bug**
Name of the clans in https://biggamesapi.io/api/clansList are all in Lowercase.

### **Current Bug:**
![Screenshot 2024-08-21 162712](https://github.com/user-attachments/assets/f2fb3508-1d42-401a-9eef-c35e89464bf6)

# **Expected behavior**
All clan names should be displayed in the correct case. 

### **Should be like this:**
![Screenshot 2024-08-21 162818](https://github.com/user-attachments/assets/d09b8812-53c8-4e09-b887-8df521179458)

### **More examples:**
- cat => CAT
- goop => Goop
- tskc => TskC
- p0ok => P0Ok

**Comment by chickenputty** [comment]
Thanks, it is fixed now

**Comment by socutewhitebear** [comment]
Thank you Adam!
