### ISSUE TITLE
public invenory

### ISSUE THREAD

**Issue by Soap-0020** [BIG-Games-LLC/ps99-public-api-docs#72]
Ive turned on the setting on the site (shown below)
![image](https://github.com/user-attachments/assets/f0e7d458-8166-458e-a79c-eb9137554761)

but whats the api to actually get the player data?
thanks

**Comment by wa1ker38552** [comment]
Are you still able to log on to the site?

**Comment by chickenputty** [comment]
Sorry this is not a part of the public API currently.

**Comment by Soap-0020** [comment]
disappointing.
