### ISSUE TITLE
mailboxes endpoint

### ISSUE THREAD

**Issue by neevesxs** [BIG-Games-LLC/ps99-public-api-docs#74]
**Question**
Hi,

I wanted to know if there's a way to track the items/diamonds sent through the mailboxes. I would like to create an automated **'balance' command** for my clan without having to log into the clan account to accept the diamonds and add them to the bot's balance.  

I saw that the **EXP clan** has something similar, and it seems to work **'automatically'** for deposits from what I could tell.

**Comment by chickenputty** [comment]
No, currently the API is for our configuration data only. This probably will never happen, sorry. It definitely would be insanely cool.

I imagine the other clan does it with macros and OCR, or they are using scripts (cheating).
