### ISSUE TITLE
Make various changes to docs.biggamesapi.io

### ISSUE THREAD

**Issue by editlt** [BIG-Games-LLC/ps99-public-api-docs#77]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
If ps99.biggamesapi.io is going to be recommended for the 99 Production environment, all the links for each cURL and each sub category should be changed to add the new subdomain. Also, personally, I cannot understand what "pt": 1 or "pt": 2 means (I assume it's rainbow or golden?). Could this be more documented somewhere, or changed to something else?

**Comment by chickenputty** [comment]
We will remain backwards compatibility, so the non-subdomain will lead to ps99 by default. I updated it the docs to ps99 subdomain now.

For the variants, pt 1 is golden and pt 2 is rainbow.

Such as:
```javascript
        const { pt, sh } = dataItem.configData;
        if (!pt && !sh) {
            addField('Regular', dataItem);
        } else if (pt === 1 && !sh) {
            addField('Golden', dataItem);
        } else if (pt === 2 && !sh) {
            addField('Rainbow', dataItem);
        } else if (!pt && sh) {
            addField('Shiny', dataItem);
        } else if (pt === 1 && sh) {
            addField('Shiny Golden', dataItem);
        } else if (pt === 2 && sh) {
            addField('Shiny Rainbow', dataItem);
        }
```
