### ISSUE TITLE
Support/Feature Site Request

### ISSUE THREAD

**Issue by Soulivan71** [BIG-Games-LLC/ps99-public-api-docs#78]
I want to make a bot that inspect my inventory through : https://db.biggames.io/player/201444514
But can't afford the others pages. I don't find a solution to get the data / from the others pages.
Can u change ur paging system. Or maybe do u have an endpoint where I can get every pets of my inventory and then cached it. 
To make what I want. 

A discord bot announcing when I get new huge (wich huge/name/variants/and pic of it) + Could u help me to find a solution ?

Changing the page system maybe more easier I don't know

**Comment by Soulivan71** [comment]
[Suggestion]:
Add an option to display more than 36(thats is actual number) ±
Add filter (shiny/shinyRB/shinygold etc) Like this => ![image](https://github.com/user-attachments/assets/21cf624f-46b1-4cad-88fd-d3c2f8106068)

**Comment by editlt** [comment]
Putty has addressed this,

              We will not expose player data to the public. We are thinking about access to player information through Roblox's OAuth 2.0 system. This is a bigger undertaking and is something we will explore eventually.

_Originally posted by @chickenputty in https://github.com/BIG-Games-LLC/ps99-public-api-docs/issues/5#issuecomment-1989614992_

Web scraping is usually not effective and it's not conventional, and an API for this isn't public. Whether or not putty has something else to say and if they plan to expose any player's data to the public (which probably isn't going to happen as it's a setting to see someone else's inventory which is a setting on db.biggames.io).

**Comment by chickenputty** [comment]
Sorry this is not a part of the public API currently.
