### ISSUE TITLE
return 0 or N/A when the value doesnt exist

### ISSUE THREAD

**Issue by dortik98** [BIG-Games-LLC/ps99-public-api-docs#8]
**Is your feature request related to a problem? Please describe.**
The problem with, for example the clan API is, whenever the clan doesnt have a bronze, silver or gold medal, the value just is not there.

**Describe the solution you'd like**
Id like for the API to return 0 or other alternatives. For medals, use 0. for other things like total points earned at a previous clan battle, use N/A or something similar.

**Additional context**
I know this can be fixed by myself using alternatives for the embeds, but the tool I am using does not support that.
Ive added a screenshot of what the medals and christmas 2023 clan battle looks like for my clan (i dont have either medals and the clan did not exist when the christmas 2023 battle happened.
![Discord_FH1PxMZtSo](https://github.com/BIG-Games-LLC/ps99-public-api-docs/assets/68707985/6e2444c0-010d-41d8-a1ee-48030742b4d2)
![Discord_qWdoQTowyR](https://github.com/BIG-Games-LLC/ps99-public-api-docs/assets/68707985/0dbab315-4d1e-4026-ad7c-d31e3ab60568)

**Comment by chickenputty** [comment]
This is handled easily with code. What are you using?

**Comment by dortik98** [comment]
> This is handled easily with code. What are you using?

Hey! Thanks for the reply.
Im not using actual code, im using BotGhost. Im kinda lazy to actually learn code, even though I really want to. I was trying for months to conatct you on Discord but you have friend reauests off lol.
Anyways, I checked the tools they have and its not possible.

**Comment by chickenputty** [comment]
Not sure, best to ask through BotGhost support - https://discord.com/invite/botghost

We do not store the data (0 medals), so it's not something we would be adding.

**Comment by dortik98** [comment]
> Not sure, best to ask through BotGhost support - https://discord.com/invite/botghost
> 
> 
> 
> We do not store the data (0 medals), so it's not something we would be adding.

Sorry for still replying even after the issue was closed. Any way I could contact you on Discord?
