### ISSUE TITLE
Written Consent for API

### ISSUE THREAD

**Issue by TotoroSides** [BIG-Games-LLC/ps99-public-api-docs#80]
Hey! 

Within the Terms of the API it does state that you require written permission for commercial use. I'm currently creating a Discord Bot for PS99, which has been manually coded from the ground up for the last couple months, I was wondering if it possible to the written consent for commercial use as I would like to add a minor (completely optional) paywall/"support us" feature (again, optional)?

The possible paywall feature would grant further access to information such as Clan Info if your Clan is outside the top 800, for example. If the Clan is within the top 800, you would be able to see the public information of it for free regardless. Any and all monies made would go directly towards server and data storage for the bot. 
All attribution and credit will be listed for Big Games LLC too. 

If any of this is an issue, please let me know and I would be more than happy to discuss what could be done 🙂 Thank you!

**Comment by chickenputty** [comment]
![image](https://github.com/user-attachments/assets/586d71fa-38a4-4bda-b107-9e4f50ff347b)

**Comment by TotoroSides** [comment]
Thank you so much!
