### ISSUE TITLE
format values, add values for the top perfomers in clan battles, give us a way to get the persons username directly instead of an ID

### ISSUE THREAD

**Issue by dortik98** [BIG-Games-LLC/ps99-public-api-docs#9]
Format values like diamonds from 1000000 to 1,000,000 or similar;

Add values or sort point contributions in the order of top from worst performers;

Add values for the persons usernames, not just IDs. I have to contact the roblox API additionally to get the persons username instead of the ID.

**Comment by Soap-0020** [comment]
for formatting, you can use your programming language
eg for javascript: 
`const value = 1000000
console.log(value.toLocaleString()) //1,000,000 `

**Comment by chickenputty** [comment]
- Values will remain as integers as they are numbers. You may locale format them as you wish.
- We deliver the data as it is stored. You may sort them as you wish.
- This request is out of scope for the Pet Simulator 99 API. Please refer to the Roblox API to resolve ID to name.
